(function(root){
  'use strict';
  const friends={
    thack:{name:'Thack',color:'#c5a0ff',second:'#6cdbda',champ:'veigar',pokemon:'gyarados',symbol:'✧',title:'The Missing Lecturer',quote:'I’ll be back.',win:'He came back. And somehow brought the right answer.',miss:'The teacher has temporarily left the classroom.'},
    isaac:{name:'Isaac',color:'#8ce8ce',second:'#aabfff',champ:'karma',pokemon:'groudon',symbol:'◇',title:'Peak Hour',quote:'I smurf your peak.',win:'Diamond behavior. Isaac will absolutely mention this.',miss:'The commute to the correct answer continues.'},
    ryan:{name:'Ryan',color:'#ffca87',second:'#f28c9b',champ:'ksante',pokemon:'pancham',symbol:'▱',title:'The Cardboard Exchange',quote:'Yo boom. Ballright.',win:'Yo boom. That answer is mint condition.',miss:'That guess has been listed below market value.'},
    brent:{name:'Brent',color:'#ff99a8',second:'#76d5ad',champ:'aatrox',pokemon:null,symbol:'⚔',title:'The Eternal Promotion',quote:'When’s mix?',win:'Promotion secured. Please remain calm in the group chat.',miss:'Income comparison will not open this lock.'}
  };
  // Theme mascots never enter the answer roster. Pancham and Groudon are decoration only.
  const themes={
    wordle:{friend:'isaac',name:'Peak Performance',motif:'diamond',line:'Five letters. Diamond confidence.',detail:'Karma keeps the peace. Isaac starts the argument.',art:'karma.jpg',win:'Five letters above your peak.'},
    categories:{friend:'ryan',name:'The Trade Binder',motif:'cards',line:'Sort the binder. Check the comps.',detail:'Ryan’s trading desk · mint-condition connections.',art:'pancham.png',win:'Four complete sets. Ryan is checking resale.'},
    ladder:{friend:'thack',name:'The Long Way Back',motif:'steps',line:'“I’ll be back.” Estimated arrival: unknown.',detail:'Minecraft, Terraria, then class. Thack is on his way.',art:'zyra.jpg',win:'Thack actually made it back.'},
    codebreaker:{friend:'brent',name:'Emerald Security',motif:'lock',line:'The rank is locked. The code doesn’t have to be.',detail:'Brent’s promotion gate · salary verification unnecessary.',art:'aatrox.jpg',win:'One lock opened. The Emerald border remains.'},
    anagrams:{friend:'isaac',name:'Stir the Chat',motif:'signal',line:'Rearrange the letters. Instigate responsibly.',detail:'A Deadlock intermission. Isaac has entered the argument.',art:'karma.jpg',win:'The argument has been alphabetically resolved.'},
    hive:{friend:'ryan',name:'The Boom Room',motif:'pulse',line:'Yo boom. Seven letters. Ballright.',detail:'Ryan’s Black Desert break. Minecraft can wait.',art:'pancham.png',win:'Yo boom. That’s a whole hive.'},
    crossword:{friend:'brent',name:'The Mix Schedule',motif:'grid',line:'When’s mix? After one more clue.',detail:'Brent’s crimson crossword desk.',art:'aatrox.jpg',win:'Every square is filled. Now, when’s mix?'},
    logic:{friend:'thack',name:'Office Hours',motif:'chalk',line:'The teacher is in. Probably.',detail:'Thack’s logic class · attendance is a gamble.',art:'veigar.jpg',win:'Full marks. Teacher spotted leaving immediately.'},
    'rift-classic':{friend:'brent',name:'Emerald Forever',motif:'blade',line:'Aatrox energy. Emerald residency.',detail:'Brent’s ranked archive.',art:'aatrox.jpg',win:'Champion identified. Promotion still pending.'},
    'rift-quote':{friend:'thack',name:'The Substitute Sorcerer',motif:'runes',line:'Small mage. Big lesson. Missing teacher.',detail:'Veigar’s classroom, unofficially supervised by Thack.',art:'veigar.jpg',win:'Veigar has graded the assignment.'},
    'rift-ability':{friend:'isaac',name:'The Karma Curriculum',motif:'aura',line:'The kit that climbed. The peak that got smurfed.',detail:'Isaac’s Diamond study guide.',art:'karma.jpg',win:'That ability was beneath your peak.'},
    'rift-emoji':{friend:'ryan',name:'Top Lane Translator',motif:'impact',line:'No distance. Just hands. Yo boom.',detail:'K’Sante takes the front line for Ryan.',art:'ksante.jpg',win:'Ballright. You speak fluent top lane.'},
    'rift-splash':{friend:'squad',name:'The Loading Lobby',motif:'signal',line:'Four friends. One more queue.',detail:'Everyone is ready. Thack said he’ll be back.',art:'viego.jpg',win:'Everyone loaded in. It’s a miracle.'},
    'dex-classic':{friend:'thack',name:'The Gyarados Register',motif:'water',line:'Attendance: 151. Thack: missing.',detail:'Gyarados guards the field register.',art:'gyarados.png',win:'Entry complete. Gyarados gets full marks.'},
    'dex-card':{friend:'isaac',name:'The Felt-Hat Collection',motif:'foil',line:'A collector’s eye. Diamond standards.',detail:'A felt-hat nod to Isaac, with Groudon on the shelf.',art:'pikachu.png',extra:'groudon.png',win:'A pull worth the commute.'},
    'dex-description':{friend:'ryan',name:'The Panda’s Field Notes',motif:'paper',line:'Read the fine print before buying.',detail:'Pancham minds Ryan’s shop. Every answer is still Gen 1.',art:'pancham.png',win:'Identification confirmed. Ryan has priced the card.'},
    'dex-silhouette':{friend:'brent',name:'The Borrowed Pokédex',motif:'scan',line:'Brent borrowed the Pokédex. Good luck.',detail:'Charizard supervises a very confident beginner.',art:'charizard.png',win:'Brent has successfully learned one Pokémon.'},
    'dex-types':{friend:'squad',name:'The Group Field Trip',motif:'radar',line:'Bring the Pokédex. Leave the arguments.',detail:'Blastoise leads a suspiciously unqualified research team.',art:'blastoise.png',extra:'eevee.png',win:'The group project somehow got an A.'},
    cryptic:{friend:'brent',name:'The After-Hours Exam',motif:'vault',line:'Hard questions. Unranked answers.',detail:'The archive’s hardest word game. Emerald ego optional.',art:'aatrox.jpg',win:'The vault opened. Even Brent went quiet.'}
  };
  const trails=[
    {id:'missing',friend:'thack',title:'The Missing Lecturer',difficulty:'Easy',symbol:'✧',seal:'LOVE',intro:'A teacher promised to return. Trace the route he left behind.',steps:[
      {game:'ladder',location:'I climb without feet; each rung changes one letter. Begin where a word takes small steps toward another.',where:'Find Word Ladder in Word & logic.',title:'An empty classroom',kind:'Riddle',question:'I’m a promise made before a disappearance. Complete the teacher’s three-word exit line.',answers:['illbeback','iwillbeback'],hint:'I’ll ___ ____.',evidence:'“I’ll be back” — a promise with no return time.'},
      {game:'rift-quote',location:'A tiny sorcerer teaches a lesson in the Rift. Find the game where a champion speaks in riddles.',where:'League → Quote & Riddle.',title:'The substitute',kind:'Quiz',question:'Two champions are on this teacher’s favorites list. One grows a dangerous garden; the other is a tiny master of evil. Name either one.',answers:['zyra','veigar'],hint:'The garden belongs to Zyra. The little mage is Veigar.',evidence:'Veigar and Zyra are on the teacher’s favorites list.'},
      {game:'dex-classic',location:'Trade the purple classroom for a blue sea serpent. Its register compares six facts about every guess.',where:'Kanto → Classic, the Gyarados Register.',title:'The attendance register',kind:'Riddle',question:'A humble fish becomes my furious form. I’m the sea serpent on the teacher’s favorites list. Who am I?',answers:['gyarados'],hint:'Starts GYA. The mascot is watching the register.',evidence:'Gyarados is the missing lecturer’s favorite Pokémon.'},
      {game:'logic',location:'Return to office hours. Three trainers have muddled their partners and destinations; the teacher left a note beside their evidence.',where:'Word & logic → Logic Lab.',title:'The lesson plan',kind:'Word puzzle',question:'Pokémon packs and CS cases: the teacher likes taking a chance. Rearrange GARWE into the five-letter verb for putting something on the outcome.',answers:['wager'],hint:'Starts W. It is another word for bet.',evidence:'The lecturer’s other lesson is about taking a wager.'}
    ]},
    {id:'peak',friend:'isaac',title:'Peak Hour',difficulty:'Medium',symbol:'◇',seal:'ALL',intro:'Follow a trail of big claims, a long commute, and one very successful champion.',steps:[
      {game:'anagrams',location:'Someone has stirred the chat and scattered five words. Start where mixed letters are put back in order.',where:'Word & logic → Anagram Rush.',title:'Rush hour',kind:'Anagram',question:'A boast was broken into tiles: M O D A I N D. Rearrange them into this friend’s League rank.',answers:['diamond'],hint:'A rank and a precious gemstone. It starts with D.',evidence:'This friend reached Diamond.'},
      {game:'rift-ability',location:'The next lesson is in the kit that climbed. Look for the jade champion, then inspect her ability archive.',where:'League → Ability, the Karma Curriculum.',title:'The climb',kind:'Quiz',question:'I’m both a champion and the idea that actions bring consequences. I was this friend’s route up the ranked ladder. Name me.',answers:['karma'],hint:'Five letters. Begins K.',evidence:'Karma carried this friend’s climb.'},
      {game:'dex-card',location:'Leave the Rift for a collector’s shelf. The next evidence is behind a blurred mystery card and a little felt hat.',where:'Kanto → Mystery Card.',title:'A familiar hat',kind:'Quiz',question:'This friend doesn’t collect every Pokémon, but really likes the felt-hat card. Which Pokémon wears that hat?',answers:['pikachu'],hint:'The yellow electric mascot, not Groudon.',evidence:'A felt-hat Pikachu card has a special place on the shelf.'},
      {game:'wordle',location:'Five letters and six chances wait at the arcade’s original ritual. Diamond confidence followed you there.',where:'Word & logic → Wordle.',title:'Above the summit',kind:'Cipher',question:'Every letter in this message is one step too far through the alphabet. Move each back one: J TNVSG ZPVS QFBL. Enter the decoded boast.',answers:['ismurfyourpeak'],hint:'J becomes I; TNVSG becomes SMURF. Keep the word boundaries.',evidence:'“I smurf your peak.” The commuter has arrived.'}
    ]},
    {id:'exchange',friend:'ryan',title:'The Cardboard Exchange',difficulty:'Medium',symbol:'▱',seal:'MY',intro:'A card trader has hidden the evidence between binders, field notes, and the front line.',steps:[
      {game:'categories',location:'Four sets are mixed in one binder. Start at the desk where sixteen words need sorting into families.',where:'Word & logic → Category Match.',title:'The market opens',kind:'Quiz',question:'The trader’s favorite has a leaf in its mouth and a little panda attitude. Name the Pokémon guarding his desk.',answers:['pancham','panchamp'],hint:'Pancham. The spelling “Panchamp” also counts here.',evidence:'Pancham is this trader’s favorite Pokémon.'},
      {game:'dex-description',location:'The little panda has more paperwork. Look for the Kanto book where written field notes describe the answer.',where:'Kanto → Description, The Panda’s Field Notes.',title:'A note in the margin',kind:'Hidden phrase',question:'Read only the capital letters: eYes cOuld Be hiding sOmething in these Odd Margins. What two-word greeting appears?',answers:['yoboom'],hint:'Y O B O O M. Put a space after the first two letters.',evidence:'“Yo boom” is the trader’s greeting.'},
      {game:'rift-emoji',location:'Leave the shop and head straight to the front line. Find the top laner’s translation desk, where champions become symbols.',where:'League → Emoji, Top Lane Translator.',title:'Up close',kind:'Quiz',question:'This friend likes top lane and close-range champions. The theme’s defender has a name with an apostrophe. Name that champion.',answers:['ksante'],hint:'K’Sante. Punctuation does not matter.',evidence:'K’Sante represents the trader’s up-close top-lane style.'},
      {game:'hive',location:'A boom echoes inside seven honeycomb letters. The word collector left his last sound bite there.',where:'Word & logic → Letter Hive, The Boom Room.',title:'One last sound bite',kind:'Assembly',question:'Join BALL to RIGHT. Enter the random word this friend says.',answers:['ballright','balright'],hint:'The spoken joke is “ballright”; the familiar spelling is accepted.',evidence:'“Ballright” — the trader’s other signature sound.'}
    ]},
    {id:'promotion',friend:'brent',title:'The Eternal Promotion',difficulty:'Hard',symbol:'⚔',seal:'KITTENS',intro:'A promotion is missing. Its owner insists the queue, the salary, and everyone else are responsible.',steps:[
      {game:'crossword',location:'The group’s next session is hiding in a schedule of crossing words. Start where across meets down.',where:'Word & logic → Mini Crossword, The Mix Schedule.',title:'The calendar invite',kind:'Acrostic',question:'Read the first letter of every word: When Heroes Enter Night, Summoners Meet In Xeniality. What question does the group always hear?',answers:['whensmix','whenismix'],hint:'W H E N S M I X. Add an apostrophe and a space.',evidence:'“When’s mix?” is the standing calendar invite.'},
      {game:'rift-classic',location:'Follow the crimson blade into the champion register. Six colored facts guard the next clue.',where:'League → Classic, Emerald Forever.',title:'The signature pick',kind:'Extraction',question:'Only the repeated letter survives each pair: cAa, rAa, nTt, pRr, sOo, vXx. Read the six survivors as one champion name.',answers:['aatrox'],hint:'In cAa, A/a is repeated. Repeat that rule for each group.',evidence:'Aatrox is this player’s signature champion.'},
      {game:'dex-silhouette',location:'Our swordsman borrowed a Pokédex and forgot to turn on the light. Find the cropped shadow under Charizard’s supervision.',where:'Kanto → Who’s That Pokémon?',title:'Expert in one field',kind:'Logic quiz',question:'A label must be accurate: “Kanto collector”, “Pokémon expert”, or “League regular”. Based on this friend’s interests, which label fits?',answers:['leagueregular','league'],hint:'He plays League almost all the time and doesn’t know much about Pokémon.',evidence:'A League regular; Pokémon expertise was borrowed with the device.'},
      {game:'codebreaker',location:'Return to the promotion gate. Four digits guard the lock, but the archive’s gemstone sits beside it.',where:'Word & logic → Codebreaker, Emerald Security.',title:'Permanent residence',kind:'Anagram',question:'Rearrange DREAM + EL into the seven-letter rank that has become this friend’s permanent address.',answers:['emerald'],hint:'It is a green gemstone. Begins E.',evidence:'Emerald has become a very long-term residence.'}
    ]}
  ];
  const api={friends,themes,trails};if(typeof module==='object'&&module.exports)module.exports=api;else root.SquadData=api;
})(typeof window!=='undefined'?window:globalThis);
